### ISSUE TITLE
Star Citizen Launcher is just white with wine-runner-6.4-gold-fsync

### ISSUE THREAD

**Issue by ErikSteiner** [snatella/wine-runner-sc#1]
**Runner Name/Version**
wine-runner-6.4-gold-fsync

**Distro/Version**
Manjaro Ornara 21.0

**Graphics**
Nvidia 460.56

**Describe the bug**
Star Citizen Launcher is just a white box.

**Performed actions**
Install Star Citizen via Lutris install script and launch Star Citizen launcher. Everything looks good, as it uses the lutris 5.7 runner by default. Switch to wine-runner-6.0-gold-fsync. Everything looks fine. The launcher is working as expected. Launch the SC launcher with wine-runner-6.4-gold-fsync and the launcher is just white. However the "launch" button works, so this seems like a visual issue.

**Logs/Screenshots**
![Star Citizen Launcher](https://user-images.githubusercontent.com/2684018/113451219-d2f3c000-9401-11eb-8fe5-e10819ad93d0.png)

**Comment by snatella** [comment]
Hey @ErikSteiner if you add `--use-gl=osmesa` to the launch arguments, does it fix it? I think someone told me it was fixed, I removed it from the notes, but I didn't find it in my testing as my lutris had it left in.

**Comment by ErikSteiner** [comment]
Thank you. Adding `--use-gl=osmesa` to the game options tab of Lutris did it.

**Comment by snatella** [comment]
@ErikSteiner @misterio77 I've updated the release notes to include that again.
