### ISSUE TITLE
WineDbg - a program on your system has crashed

### ISSUE THREAD

**Issue by emilwojcik93** [snatella/wine-runner-sc#3]
**Runner Name/Version**
wine-runner-6.10-gold-fsync.tgz
wine-runner-6.6-gold-fsync.tgz
wine-runner-6.5-gold-fsync.tgz
wine-runner-6.0-gold-fsync.tgz
(I thing any version, those above I checked)

**Distro/Version**
Manjaro 21.0.7 (5.10.42-1-MANJARO) - current OS
Pop!_OS 21.04

**Graphics**
NVidia GeForce GTX 1660 SUPER (video-nvidia proprietary driver)

**Describe the bug**
I installed Star Citizen using "clean" script from Lutris (only declared Wine runner), then I used modified version of [script](https://pastebin.com/2hkTMTGm) by myself also change report different system (win7, win8) but every time on last step "Installing client" I receive error:

"A program on your system has crashed, but WineDbg was unable to attach to the process to obtain a backtrace"

[Here](https://pastebin.com/2PZgZXTy) is full log from lutris console from this step.

[Here](https://www.reddit.com/r/linux_gaming/comments/ohpvr2/star_citizen_installation_problem/) is described more precisely what I was tried to do.

Exactly I don't know is this runner issue or just my PC config or my methods of game installation?

Please help and best regards,
emilwojcik93

**Comment by emilwojcik93** [comment]
Hello,
I've been able to run game but this was very slow and difficult process.
I've to:
1. install game using [lutris script](https://pastebin.com/y0VqxsYj) with lutris runner
2. login to RSI Launcher
3. reinstall game using [lutris script](https://pastebin.com/JAa4nYJd) with wine-runner-sc
4. install Star Citizen through RSI Launcher
5. launch Star Citizen

But this is not resolve the issue because I've to used different runner to setup client (RSI Launcher) and this is only bypass, temporary way to run Star Citizen.

**Comment by snatella** [comment]
Hello @emilwojcik93,

I believe from what I'm hearing on Spectrum you have got this working in discord? Can you confirm?

At this time only my https://github.com/snatella/wine-runner-sc/releases/tag/wine-v6.6 would be the recommended way to install in a fresh prefix, if you've changed runners during install you may have corrupted your wine prefix (it's not a precise art unfortunately!).

Our biggest issue at the moment, is there is no Lutris wine runner that works with Star Citizen! So our hands our somewhat tied on making installation nice and easy.

Let me know.

**Comment by emilwojcik93** [comment]
Yes, currently game works for me with this runner but I've to setup game and install RSI Launcher with different runner and play game with wine-runner-sc. I suggest that there should be installation instruction in README.md.

This is my instllation config:
https://pastebin.com/y0VqxsYj
This is my config for gaming:
https://pastebin.com/JAa4nYJd

Here is more info about whole process:
https://www.reddit.com/r/linux_gaming/comments/ohpvr2/star_citizen_installation_problem/

Also I suggest to add info about lug-helper and how to manually install wine-runner-sc for lutris.

If you think this idea is unconvintient then I could make separate repo on github about this.

**Comment by snatella** [comment]
Sorry I didn't get back to you, apparently I need to fix my github notifications. I've retired my involvement in building wine runners at this time. The issues surrounding our original problem are now past and there are many great runner options in the lug-helper :)
