### ISSUE TITLE
Better performance on wine-ge-custom

### ISSUE THREAD

**Issue by emilwojcik93** [snatella/wine-runner-sc#4]
Hello,
Could you build runner on [this repo Wine-6.12-GE-1](https://github.com/GloriousEggroll/wine-ge-custom) ? Idk is this matter of newer version of wine 6.12 or this specific runner but I've much better performance compared to wine-runner-6.6-gold-fsync but there is also issue with in-game touch screens / panels usage, right mouse button doesn't work.
So I been thinking that build Wine-6.12-GE-1 with patches from wine-runner-6.6-gold-fsync should be perfect solution for Star Citizen 3.13.1.

Could You help me with this request?
Also I'll be very grateful for any tutorials for different manuals about wine runners and how this is works.

Thank you and best regards,
emilwojcik93

**Comment by snatella** [comment]
Hello @emilwojcik93,

So GE uses a version of wine with lots of staging and proton patches included. These are over and above the ones I add (so he has my patches _and some_ - excluding possibly the joyaxis but that does not affect performance). Between GE and TkG they will also add custom patches and reverts in to aid and help performance, whereas I tend to stick to mainline wine to save my time! Those guys are great and crazy with the amount of time/effort they put in.

- I'd raise a bug with GE about the in-game touch panels.
- Me making a 6.12 build with his base would just be what he already builds.

Unfortunately I don't have the time to dedicate to tutoring on what I know - but I can share where I started from which should give you a good starting point.

- https://wiki.archlinux.org/title/wine - the Arch wiki covers a lot of good wine basics.
- https://github.com/wine-mirror/wine - wine source on github, a good place to start poking around with building.
- https://github.com/wine-staging/wine-staging - where a number of "staging" patches live that aren't ready for mainline, but often include things people generally use like esync.
- https://github.com/ValveSoftware/Proton - a superset of wine, staging and Valve's many additions. fsync is from here, but some patches aren't as simple as lift and throw onto "vanilla" wine!
- https://wiki.winehq.org/Building_Wine - the mother of all build guides (for wine at least), local compilation will always give you best compatibility.
- TkG creates Arch friendly runners, e.g. https://github.com/Frogging-Family/wine-tkg-git/releases/tag/6.11.r4.g0dd44a25, I believe some of the assets can be used with pacman or something? I don't know Arch in the slightest, sorry!

As it stands people with more time to develop build systems are appearing on the scene, so what I've got within this repository and `wine-builder-ubuntu-docker` is probably going to go out of date quite quickly, but it might give you some ideas if you get to the building wine for other people part ;-)

I wish you luck in your learning!
